### ISSUE TITLE
Non-descriptive variable names

### ISSUE THREAD

**Issue by eric-at-zd** [tipenehughes/pokedex-zaf#1]
Being pretty nit picky here so apologies, though I can make sense of your variable names [here](https://github.com/tipenehughes/pokedex-zaf/blob/dc319f27b74af3559a7aa860efa647b2dbb92ba0/pokemon%20object/main.js#L6) and understand why you trimmed them further. Though as a best practice try using slightly more descriptive names (pokeData, pokeResp).

**Comment by tipenehughes** [comment]
Updated to [pokeData, pokeRes], [speciesData, speciesRes], [evolutionData, evolutionRes]
