### ISSUE TITLE
Adjust index.html reference to boilerplate you used

### ISSUE THREAD

**Issue by eric-at-zd** [tipenehughes/pokedex-zaf#2]
[Your src file is still referencing the boilerplate you used](https://github.com/tipenehughes/pokedex-zaf/blob/dc319f27b74af3559a7aa860efa647b2dbb92ba0/src/index.html#L6). You'll also want to remove the remote orgin as it's also referencing the boilerplate. This is why your contributors are showing 5 other people.

**Comment by tipenehughes** [comment]
Updated. New repo to be published
